### ISSUE TITLE
[Firefox addon] Add a button on PlayStore/F-Droid to allow remote app downloading 

### ISSUE THREAD

**Issue by nicolasmaia** [GSConnect/gnome-shell-extension-gsconnect#1040]
It would be cool if the browser extension added a button on the Play Store website, F-Droid and perhaps [Fossdroid](https://fossdroid.com) to allow downloading an app from another device.

It could either send a link to download the apk directly or a link to the app store so the device would download it. For F-Droid, it might require the [F-Droid Privileged Extension](https://f-droid.org/en/packages/org.fdroid.fdroid.privileged/).

**Comment by ferdnyc** [comment]
@nicolasmaia For anything other than merely sending a web link to the download page (which you can already do, using the browser extension), the feature would have to first be supported in the KDE Connect Android app. GSConnect can only make use of the APIs provided by the app.

The best approach would be to submit a feature request for KDE Connect's Android app in [the KDE bug tracker](https://bugs.kde.org/buglist.cgi?component=android-application&product=kdeconnect&bug_status=__open__), or check whether the idea has already been proposed and provide your input. I didn't see any open issues that sounded related, in a quick scan.

(For the record, I'm not sure this would be a particularly good feature for KDE Connect. I mean, if we're talking about app store websites, in theory they can already provide that functionality all by themselves, using their own phone apps. Google Play already does, in fact.

I install phone apps from the Google Play site _**all the time**_, right from my desktop browser and without even touching my phone. Because my Google account is connected on both ends of the link, there's an "Install on ___$DEVICE___" option provided on every app page. I just choose that, and a few seconds later my phone just wakes itself up and it's done.

In theory other sites like F-Droid could do the same, and there's really no reason for KDE Connect to be involved.)

**Comment by nicolasmaia** [comment]
@ferdnyc Thanks for the feedback. The idea is that this would useful for people not relying on Google services. So such a button on the Play Store would remotely install the app in the user's app store of choice (F-Droid, Aurora Store, etc).

**Comment by ferdnyc** [comment]
> The idea is that this would useful for people not relying on Google services. So such a button on the Play Store would remotely install the app in the user's app store of choice (F-Droid, Aurora Store, etc).

@nicolasmaia Oh, wait, so you'd want to be able to download apps from one service and use a _different_ service to install them? I don't see how any of the app distribution platforms would go for that, it's a **massive** security risk. There's simply no way to verify that the file being presented to them by this untrusted, third-party service (KDE Connect) is actually a valid app and not some form of malware. Heck, most devices won't even allow apps to be installed by third parties by default, the user has to explicitly change the configuration to open up that security hole. But it feels like this would be ripping it even wider.

Well, like I said, it's up to the KDE Connect team whether or not they're willing to implement the feature.

**Comment by daniellandau** [comment]
As far as I understand, Aurora store always requires a Google account to download any apps, and if you don't provide your own they have a pool of accounts you can use. Downloading apks from the Play Store is a shifting target and it doesn't make sense for us to try to do it too.

You can already send the link and atleast firefox can then open it in aurora store if you so wish.

**Comment by nicolasmaia** [comment]
> You can already send the link and atleast firefox can then open it in aurora store if you so wish.

Right, the functionality is already there, that's why I thought it wouldn't be that much work to just put a CSS box with a button on F-Droid or Google Play pages. But I suppose that would be a job for KDE Connect.
