### ISSUE TITLE
Keyboard backspace and enter buttons

### ISSUE THREAD

**Issue by brccabral** [GSConnect/gnome-shell-extension-gsconnect#1197]
When using remote control I can use my phone keyboard to type letters, numbers and special characters, but if I make a mistake I can't use the backspace button to correct my typing and neither use enter button to add a new line.

Is it a bug or expected behavior?

GSConnect 48
KDE Connect 1.17
Ubuntu 20.04
Galaxy S20 Android 11

**Comment by andyholmes** [comment]
This feature should work, as far as I know. Please provide a log as described in the Wiki page [Generate Support Log](https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Help#generate-support-log).

**Comment by piviul** [comment]
the same happens to me even if it is not so simple as brccabral describe... I use gsconnnect 45 on a debian bullseye. Not only backspace doesn't works but even the space didn't; furthermore even the click sometime doesn't behave as expected. For example I can't power of the pc because if I click on the upper right gnome shell bars clicking on the power off item do nothing except close the menu. Both keyboard typing and clicking problems doesn't behave the same in every context: normally click works (I found click problems only in gnome shell menus) and typing backspace or space in gnomeshell find textbox works but in most programs (like firefox or gedit) didn't. This is the log you required:
[gsconnect.log](https://github.com/GSConnect/gnome-shell-extension-gsconnect/files/7855577/gsconnect.log)

**Comment by andyholmes** [comment]
This seems to work for me just fine. I'm typing this comment in with remote input. Backspace and enter both work fine, including GNOME Shell menus and such.

It seems like your log only includes lots of mouse movement with a single click at the very end. Can you collect a log with the events that are causing you problems and report whether you are using Wayland or X11?

**Comment by piviul** [comment]
The log should contain both problems I described you: the click problem 
and the keyboard typing problem. I don't think a new log should be 
different any way I try to send you again as soon as possible. I would 
only add that I have this problem after upgrading my debian to bullseye 
and so gsconnect to 45

Best regards

Piviul

**Comment by piviul** [comment]
I Have generated a new log; I add that even the return key doesn't work

[gsconnect.log](https://github.com/GSConnect/gnome-shell-extension-gsconnect/files/7856510/gsconnect.log)

Best regards 

Piviul

**Comment by piviul** [comment]
I forgot to say you that, as you can see from logs, I use X11.
This logs should contain only keyboard logs, I attacched a mouse and a keyboard to the PC now..
[gsconnect.log](https://github.com/GSConnect/gnome-shell-extension-gsconnect/files/7856640/gsconnect.log)

what version of gsconnect are you using? Whats the program you used to write the email?

**Comment by andyholmes** [comment]
> what version of gsconnect are you using? Whats the program you used to write the email?

I installed the latest, which is v48. I just used the KDE Connect Android app to test.

> I forgot to say you that, as you can see from logs, I use X11.

As for the keyboard problem, this seems to be a problem in the X11 backend for Mutter's RemoteDesktop, specifically with the xkb KeyMap code. It's hard to say if this has been fixed and if so, if it can be backported to Bullseye since that seems to be using mutter7 (GNOME 3.38). This error code is the hint for that:

    gen 12 18:45:01 /usr/libexec/gdm-x-session[2968]: [xkb] BOGUS LENGTH in SetMap: expected 268 got 1292

Unfortunately, there's not much we can do about this in GSConnect. I'd advise you either try a Wayland session, or upgrade your distribution. The only other option would be to see if a fix can be backported in Bullseye, since this bug will also affect any other remote desktop software under X11.

Sorry about that!

**Comment by piviul** [comment]
On 12/01/22 19:51, Andy Holmes wrote:
> [...]I'd advise you either try a Wayland session, or upgrade your 
> distribution. 
using wayland doesn't solve the problem: I fear I have to upgrade to 
bookworm...

Thank you very much Andy!

Piviul

**Comment by ferdnyc** [comment]
@piviul

If you want to sort of prove to yourself that this affects more than just GSConnect, and maybe collect some additional debugging info for your distro, you can experiment with Mutter's remote desktop interface directly over the same D-Bus connection GSConnect uses. (Alternately, if you find you _don't_ have any problems testing this way, then more investigation might be warranted.)

If you install the `d-feet` package, which should be in any distro's package collection, you can use it to access any available D-Bus interface. Here I've already switched to the Session bus and done a search for "remote" to find the listener at address `org.gnome.Mutter.RemoteDesktop`. Then I open the `/org/gnome/Mutter/RemoteDesktop` interface and execute `CreateSession()` to obtain a new session token. A  refresh of the interfaces makes it visible:

![RemoteKeyboard1](https://user-images.githubusercontent.com/538020/149626188-7c19c4aa-1a55-4439-ae82-e5ad69afc350.gif)

Opening that interface, the first thing I need to do is `Start()` my session, so it'll accept input events:

![RemoteKeyboard2](https://user-images.githubusercontent.com/538020/149626203-701fc411-1f47-4749-bae5-98654de83030.gif)

Once that's done, I can use `NotifyKeysym()` to send a keyboard event. I cheated and looked up the keysym for the <kbd>Space</kbd> key earlier in the `keysym` manpage on my system (which was installed with Tk, oddly enough), in decimal it's `32`. The message also requires a boolean value for the state of the key (`0` for off/up, `1` for on/down). So I enter `32,1` for "space,down" as the arguments, then press Execute — and as you can see, that definitely works! :rofl: 

![RemoteKeyboard3](https://user-images.githubusercontent.com/538020/149626267-f4dd8f5a-ca03-48d9-99b9-ac840bfbbb84.gif)

(In fact, when I close the window the first time, it comes right back because <kbd>Space</kbd> is the activation key in the main window. I had to type <kbd>Esc</kbd> on my physical keyboard, to get Mutter to stop repeating <kbd>Space</kbd> keypress events.)

Then if you want to be a good bus client and clean up after yourself, a `Stop()` message will tell Mutter it's OK to destroy the remote token you created and delete the interface instance.

**Comment by 3ship** [comment]
I have the same issue since about two days ago. Backspace, enter, arrow keys and tab are no longer recognized.

My support log looks pretty much the same, in that the key presses appear in the log, i.e. `"specialKey": 1` but aren't executed.

I'm fairly certain that I didn't install or upgrade anything on my phone in the time frame when the error appeared. I'll [attach an upgrade log](https://github.com/GSConnect/gnome-shell-extension-gsconnect/files/8398254/upgrlog.txt) for my PC, but can already rule out the kernel, because a downgrade didn't fix the issue.

EndeavourOS, GNOME 41, Wayland session, GSConnect 49
KDEConnect 1.19.1

**Comment by JustCryen** [comment]
I've had this issue for a long time now.
I have two systems:
1 Arch on Xorg
2 EndeavourOS on Wayland
Both don't recognize "enter" and "backspace" keystrokes through the Remote input.
I've had this problem for such a longtime that I don't even think providing software versions will be helpful, it's probably more than a year at this point, maybe two.

**Comment by andyholmes** [comment]
Just gave it shot on Fedora Silverblue 36 and it worked for me. Here's what the log looks like:

```

Jun 15 17:45:52 org.gnome.Shell.Extensions.GSConnect[53019]: [/service/device.js:_readLoop:341]: LG G6: {
                                                               "id": 1655340352313,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "j"
                                                               }
                                                             }
Jun 15 17:45:54 org.gnome.Shell.Extensions.GSConnect[53019]: [/service/device.js:_readLoop:341]: LG G6: {
                                                               "id": 1655340353721,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "specialKey": 1 <= Backspace
                                                               }
                                                             }
Jun 15 17:45:57 org.gnome.Shell.Extensions.GSConnect[53019]: [/service/device.js:_readLoop:341]: LG G6: {
                                                               "id": 1655340355112,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "k"
                                                               }
                                                             }
Jun 15 17:45:59 org.gnome.Shell.Extensions.GSConnect[53019]: [/service/device.js:_readLoop:341]: LG G6: {
                                                               "id": 1655340358474,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "specialKey": 12 <= Enter/Return
                                                               }
                                                             }
```

Without logs showing an error, there's not much to debug here unfortunately. As with most other plugins, GSConnect just takes the input and passes it along to the appropriate service which is Mutter's RemoteInput interface in this case.

**Comment by andyholmes** [comment]
Closing, since there's been no confirmation this is actually a problem in GSConnect.

Feel free to re-open if you can provide logs showing an error or incorrect protocol handling.

**Comment by andyholmes** [comment]
This may be related, yes. I would guess from those logs that you're using X11, since it has re-map keys on-the-fly sometimes.

There is a upstream issue in Mutter ([mutter#1802](https://gitlab.gnome.org/GNOME/mutter/-/issues/1802)) and stalled MR that tries to address it ([mutter!748](https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/748)), but I'm afraid it's not high priority so will probably require a volunteer to pick up the MR.

**Comment by tsilvs** [comment]
Tried remote keyboard on Fedora Silverblue 40 with GSConnect 57 & KDE Connect 1.31.1 on Android. Enter button doesn't work. Other than that no issues.

**Comment by andyholmes** [comment]
There's nothing to be fixed in GSConnect, that's why the issue was closed.
