### ISSUE TITLE
sftp connection lost after 10 minutes

### ISSUE THREAD

**Issue by sebastian-387** [GSConnect/gnome-shell-extension-gsconnect#1229]
Hello dear developers!

I'm using GNOME 41.1 (Wayland) on the latest Ubuntu 22.04 development version, and GSConnect 47. My smartphone uses KDE Connect version 1.18.1 on the latest Lineage OS 18.1.

When mounting my smartphone via sftp, a successful connection is made and I can transfer files.

After **exactly** 10 min. of inactivity, the connection is severed automatically.

I'm unsure whether this is expected behaviour or a bug. If it is a bug, I wanted to report it. If it is expected behaviour, I wanted to ask whether a feature could be implemented that allows the user to set the time delay to a custom value (including "0" for no time out).

(Reason for the feature request: I want to backup my smartphone via sftp, so that whenever I trigger a backup, my phone data would be automatically backuped as well. I think this could be a common use scenario for people who don't want to backup everything into a cloud, but create their own backups locally.)

Thanks a lot! :)

**Comment by andyholmes** [comment]
This is probably out of scope for GSConnect, since SFTP mounting is offloaded to GVfs. There's really nothing to configure here on our side, sorry.

**Comment by ferdnyc** [comment]
If it's not gvfs (which I don't _think_ times out connections on its own, normally) then it may very well be the device, in which case... it's also something not under anyone's control, so the result is the same.

(Meaning, KDE Connect doesn't have any timeout code in it either, it'd likely be the device battery-saving logic that's killing the server and terminating the link.) 

Finding whatever options are available for exempting apps from power management and adding KDE Connect to the ignored/background-apps list _might_ help, if you haven't tried that @sebastian-387 .

**Comment by ferdnyc** [comment]
Ultimately, for backing up a device I think you're probably better off with a USB cable than an SFTP link. We've [discussed](https://github.com/GSConnect/gnome-shell-extension-gsconnect/issues/478#issuecomment-470677673) in the [past](https://github.com/GSConnect/gnome-shell-extension-gsconnect/issues/478#issuecomment-595025964) (and [often at](https://github.com/GSConnect/gnome-shell-extension-gsconnect/issues/478#issuecomment-595520145) considerable [length](https://github.com/GSConnect/gnome-shell-extension-gsconnect/issues/478#issuecomment-596043557)<sup>1</sup> the issues with SFTP, which stem from:
1. The fact that SFTP is not well-designed for the mobile age, being an ethernet-based  protocol that expects an always-active link
2. The KDE Connect desktop code doing a hellish amount of "stuff", in their implementation, to try and work around that reality. Some of which impacts the design of the app end as well
3. The same "stuff" being unavailable to GSConnect in its implementation, because the same things aren't supported in Gvfs. Which gives us (as @andyholmes noted) a degree of control that's effectively indistinguishable from zero.

### Notes
1. (Those links all go to different comments in issue #478, so you can just pick any one of them if you're curious, or none at all.)

**Comment by sebastian-387** [comment]
Thanks for all of your support!

I'm gonna scrap the idea and find another solution (probably adb backup).
