### ISSUE TITLE
Running on systems with both ipv4 and ipv6 addresses

### ISSUE THREAD

**Issue by coot** [GSConnect/gnome-shell-extension-gsconnect#1250]
When `gsconnect` starts on a system that has both ipv4 and ipv6 addresses, it starts to listen only only on an `ipv6` address.  When network interfaces are configured differently, it could start only on ipv4, but it should instead listen on both.

```
lsof -ni :1716
COMMAND     PID USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
gjs     1577038 coot   18u  IPv6 14921159      0t0  TCP *:xmsg (LISTEN)
gjs     1577038 coot   19u  IPv6 14921160      0t0  UDP *:xmsg 
```

**Comment by andyholmes** [comment]
Thanks for reporting.

GSConnect already accounts for this scenario for UDP sockets:

https://github.com/GSConnect/gnome-shell-extension-gsconnect/blob/75f6c2bb16173c3657113c0d78c4e9d3a12af3a2/src/service/backends/lan.js#L258-L269

As does the [GSocketListener](https://github.com/GNOME/glib/blob/f9c08308ea0c25977b4e0153e868cb0a8703b75e/gio/gsocketlistener.c#L499-L512) class for TCP connections:

```c
      /* If this socket already speaks IPv4 then we are done. */
      if (g_socket_speaks_ipv4 (socket6))
        need_ipv4_socket = FALSE;
    }

  if (need_ipv4_socket)
    /* We are here for exactly one of the following reasons:
     *
     *   - our platform doesn't support IPv6
     *   - we successfully created an IPv6 socket but it's V6ONLY
     *
     * In either case, we need to go ahead and create an IPv4 socket
     * and fail the call if we can't bind to it.
     */
```

**Comment by ferdnyc** [comment]
Yeah, the problem is that `lsof` (and the legacy net-tools binaries like `netstat` and `route`, for that matter) don't really have a "Both" socket type, so when a socket is opened in dual-mode it only shows up as an IPv6 socket. But it's listening for connections from either address family.

I'll be the first to agree it's disconcerting, especially since so many other network services — `sshd`, `pipewire` — do the opposite. Looking at the code for both `sshd` and `pipewire-pulse`, they _explicitly_ restrict their IPv6 sockets to only speak IPv6, and open separate sockets for IPv4:

`start_ip_server()` in pipewire, which is called repeatedly over a list of network addresses, binds separately to each one, explicitly restricting the sockets for IPv6 to _only_ speak IPv6.

(From [`modules/module-protocol-pulse/server.c@801`](https://gitlab.freedesktop.org/pipewire/pipewire/-/blob/23db50630d553e4f0e08e01349610403b0019cad/src/modules/module-protocol-pulse/server.c#L801) with error checking omitted):
```c
	fd = socket(addr->ss_family, SOCK_STREAM | SOCK_CLOEXEC | SOCK_NONBLOCK, IPPROTO_TCP);
		if (setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &on, sizeof(on)) < 0)
	if (addr->ss_family == AF_INET6) {
		if (setsockopt(fd, IPPROTO_IPV6, IPV6_V6ONLY, &on, sizeof(on)) < 0)
	if (bind(fd, (const struct sockaddr *) addr, get_ip_address_length(addr)) < 0) {
```

The code in `sshd.c` is effectively the same.

I only know that I've never not been able to communicate between my phone and my desktop, regardless of address family. And since the KDE Connect protocol is only meant to be used over local subnets, it doesn't _seem_ like it should matter. If we were running internet-routable services that'd be a different story, but the way things are now seems to "just work". Do you have a scenario a separate-sockets approach handles that the GSConnect one doesn't, @coot?

**Comment by coot** [comment]
I run `tcpdump` and it does not seem right to me, for some reason the data sent by `KDE Connect` is truncated at the first packet.
[gsconnect.3.zip](https://github.com/GSConnect/gnome-shell-extension-gsconnect/files/8240559/gsconnect.3.zip)
.

**Comment by andyholmes** [comment]
Well, your pcap confirms that the socket supports IPv4. This looks to me like the packet size is exceeding the MTU (eg. 1500), which probably makes this a duplicate of #1212.

It's *possible* this is GSConnect's fault, since we use some high-level abstractions when reading datagrams. But I think more likely this is a combination of a growing packet size in KDE Connect and the lower common MTU on IPv4 interfaces.

**Comment by coot** [comment]
> Well, your pcap confirms that the socket supports IPv4. This looks to me like the packet size is exceeding the MTU (eg. 1500), which probably makes this a duplicate of https://github.com/GSConnect/gnome-shell-extension-gsconnect/issues/1212.

Yes, this looks exactly like that. This issue can be closed then.
