### ISSUE TITLE
Removing the extension doesn't remove DBus file and others.

### ISSUE THREAD

**Issue by rastersoft** [GSConnect/gnome-shell-extension-gsconnect#1269]
**Describe the bug**

After uninstalling the extension, the DBus file at ~/.local/share/dbus-1/services remain, and thus the service remains announced in DBus even when there is no code for serving it.

**Steps To Reproduce:**

1. install the extension
2. uninstall the extension
4. launch d-feet
5. go to "Session bus"
6. Search for 'gsconnect'

**Expected behavior**

No service should be shown. But, instead, the gsconnect service is still announced as "activatable". Of course, any attempt to access it returns an error.

**Comment by rastersoft** [comment]
We discovered this doing some tests with an MR for integrating GSConnect with Desktop Icons NG.

https://gitlab.com/rastersoft/desktop-icons-ng/-/merge_requests/216

**Comment by andyholmes** [comment]
I'm not really an active maintainer here, so I won't reject or approve this.

My *personal* thoughts are:

* I don't think it's a good idea to be doing I/O like this on `enable()`/`disable()`, since that happens on every screen lock/unlock and session login/logout
* Without real-world testing, I'm not convinced this won't cause problems with `dbus-broker` or excessive churn for any application holding a `GAppinfoMonitor`

Two options:

* This should generally be a non-issue as long as the `org.freedesktop.DBus.ObjectManager` proxy is using `Gio.DBusProxyFlags.DO_NOT_AUTO_START` during construction and `Gio.DBusCallFlags.NO_AUTO_START` for any direct calls. Waiting for `g-name-owner` to be non-null should be an acceptable way to wait for the service to start.
* For GNOME 42 GSConnect should probably adopt the `unlock-dialog` session mode, in which case this would be "less bad" since `enable()`/`disable()` only get called on login/logout (pretty rare). It should probably be using that session mode anyways...

**Comment by rastersoft** [comment]
BTW... what is that "unlock-dialog session mode"?

**Comment by rastersoft** [comment]
Oh, I think that I found something https://gjs.guide/extensions/overview/anatomy.html#metadata-json-required

**Comment by rastersoft** [comment]
Ok, I added the "unlock-dialog" mode.

**Comment by andyholmes** [comment]
> Those files should be deleted. Is there an "uninstall" method for the extensions, called after being disabled and before being removed?

There is no counterpart to the `init()` hook, like there is with `enable()`/`disable()`, probably for a few reasons. The long story short is that there is no good way to do this, because extensions aren't supposed to be applications or install application files like this.

It's possible this could be done by the service itself, since it already [watches for the service to be uninstalled](https://github.com/GSConnect/gnome-shell-extension-gsconnect/blob/af72deda94ed66f43107df4f05bcfe7247336f57/src/service/daemon.js#L231-L235), but again some real-world testing would be required to see that this didn't break anything else. GSConnect is already stitched together by a system of duct-tape, bubblegum and twine pulleys so I'm not keen on making that more fragile :slightly_smiling_face: 

> Ok, I added the "unlock-dialog" mode.

Unfortunately the `session-modes` key won't work until `gnome-shell >= 42.0` and as far as I know GSConnect does not yet run on `gjs >= 1.71`.
