### ISSUE TITLE
Seems not to work in LibreWolf

### ISSUE THREAD

**Issue by MarcoWilli** [GSConnect/gnome-shell-extension-gsconnect#1323]
> ***ATTENTION**: GSConnect only supports the latest, stable version of GNOME. We are no longer accepting bug reports for previous versions.*

**Describe the bug**

GSConnect icon is shown but displays "Service not available"

**Steps To Reproduce:**

1. Go to LibreWolf (not flatpak version)
2. Click on GSConnect icon
3. See error

**Support Log**

Please generate a support log ([Instructions](../wiki/Help#generate-support-log)) and paste any messages related to this issue between the two ``` lines below.

Will post later as atm GSConnect does not start at all as it seems to "freeze" sometimes on my system and I did not find a way to make it work again without restarting.

```

```

**System Details (please complete the following information):**

 - **GSConnect version:** 49
   - **Installed from:** extension-manager
 - **GNOME/Shell version:** 41.5
 - **Distro/Release:** Fedora 35

**GSConnect environment (if applicable):**

 - **Paired Device(s):** Sony Xperia H3113
 - **KDE Connect app version:** 1.19.1

**Additional Notes:**

Using Wayland with latest Nvidia Driver

**Comment by ferdnyc** [comment]
@MarcoWilli 

This FAQ answer looks like [the info you need](https://librewolf.net/docs/faq/#how-do-i-get-native-messaging-to-work):

> ### How do I get [native messaging](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging) to work?
> To get native messaging to work, for example for the [Plasma Integration](https://addons.mozilla.org/en-US/firefox/addon/plasma-integration/)[](https://librewolf.net/docs/faq/#how-can-i-get-tridactyls-native-messaging-to-work-when-i-install-librewolf-with-flatpak), create two symlinks by running these commands:
> 
> ```sh
> ln -s ~/.mozilla/native-messaging-hosts ~/.librewolf/native-messaging-hosts
>
> sudo ln -s /usr/lib/mozilla/native-messaging-hosts /usr/lib/librewolf/native-messaging-hosts
> ```

**Comment by MarcoWilli** [comment]
Thanks for that hint!
I guess this is what I would have needed prior to get KeepassXC to work, too. I managed to make it work though by copying a file which was in the Firefox folder to the LibreWolf folder as I had FF installed until then.
I have installed Librewolf via their rpm repo but I can not create the second symlink because that folder does not exist on my system =(

**Comment by ferdnyc** [comment]
@MarcoWilli That should be fine, if you don't have a `/usr/lib/mozilla/native-messaging-hosts/` then you don't have any systemwide installs that would need to be linked over to LibreWolf. The ones in your home directory — including the one GSConnect installs in `$HOME/.mozilla/native-messaging-hosts/` — will be covered by the first link.

(Which, agreed, would probably also cover KeePass. I'm guessing it would use a NMH to access the secure keyring for your account, so that it can securely store encrypted passwords.)

**Comment by ferdnyc** [comment]
Ooh! However, since you're on a RedHat-based distribution, you should actually look for a `/usr/lib64/mozilla/native-messaging-hosts/`. The LibreWolf FAQ apparently doesn't account for the path differences among distros. I'm _assuming_ you'd want to link that as `/usr/lib64/librewolf/native-messaging-hosts/`... although their code, like their FAQ, may always use the `/usr/lib/` directory regardless, so it's hard to say.

You could always hedge your bets and attempt both:

```sh
sudo ln -s /usr/lib64/mozilla/native-messaging-hosts /usr/lib64/librewolf/native-messaging-hosts
sudo ln -s /usr/lib64/mozilla/native-messaging-hosts /usr/lib/librewolf/native-messaging-hosts
```

**Comment by ferdnyc** [comment]
@MarcoWilli On the assumption that linking in the Mozilla `native-messaging-hosts` directory/directories got GSConnect working in your LibreWolf installation, I'm going to close this. Feel free to reopen, if that didn't solve this issue, or open a new issue if you encounter any other problems.

**Comment by MarcoWilli** [comment]
Hi again!
I´m sorry, but I was busy so could not reply earlier.
So I did not manage to get it working yet. Although there is a `/usr/lib64/mozilla/native-messaging-hosts/`, there is no librewolf directory neither in `/usr/lib` nor in `usr/lib64`. The only paths that do exist are the ones in the home directory.

**Comment by ferdnyc** [comment]
@MarcoWilli 

Yeah, their RPM packaging is weird. _Everything_ — including shared libraries — that you'd expect to be in `/usr/lib64/` is actually all packaged into `/usr/share/librewolf/`. I... have no idea why, really.

It probably implies that the correct link location for the systemwide native messaging hosts directory would be `/usr/share/librewolf/native-messaging-hosts`, but really that's not important. At least, not for GSConnect, which relies entirely on the _user_ native messaging hosts directory. (`$HOME/.mozilla/native-messaging-hosts`, which gets softlinked as `$HOME/.librewolf/native-messaging-hosts`.) That's where it installs the `org.gnome.shell.extensions.gsconnect.json` file that configures loading of its native messaging code.

If you have the directories symlinked in your account, so that there's a readable file located at `$HOME/.librewolf/native-messaging-hosts/org.gnome.shell.extensions.gsconnect.json` with the following contents:
```json
{
    "name": "org.gnome.shell.extensions.gsconnect",
    "description": "Native messaging host for GSConnect WebExtension",
    "path": "/home/$USER/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/nativeMessagingHost.js",
    "type": "stdio",
    "allowed_extensions": [ "gsconnect@andyholmes.github.io" ]
}
```
Then Librewolf will load the native messaging component.

The other half of the equation is the browser extension, of course, which needs to be installed from [its Mozilla Add-Ons listing](https://addons.mozilla.org/en-US/firefox/addon/gsconnect/). (There's also an install button/link on the initial page of the GSConnect preferences dialog.)

If both of those components are in place, and GSConnect is enabled and working as a Shell extension, then the browser integration should be fully functional.

**Comment by MarcoWilli** [comment]
Hm. There was no such file `$HOME/.librewolf/native-messaging-hosts/org.gnome.shell.extensions.gsconnect.json` so I created it manually and put the content in it. Then I reinstalled the browser plugin. Still did not work. Then I opened the GSConnect preferences dialogue and the formerly created file got disappeared! o.O

**Comment by ferdnyc** [comment]
Hrm. That's... curious.

(One thing I'll note, if you used the content from my comment I may have inadvertently misled you by using `$USER` as a placeholder since I don't know your username on the system in question. You'd probably need to replace `/home/$USER` with the actual disk path to your home directory; I don't think environment variables are parsed there. In my own copy of the file, the `"path"` contains `"/home/ferd/.local/share/..."`.)

But setting that aside, the only thing that would cause `/home/______/.mozilla/native-messaging-hosts/org.gnome.shell.extensions.gsconnect.json` to be _removed_ is if GSConnect is running as a system extension. IOW, it's actually installed to `/usr/share/gnome-shell/extensions/` (probably by a distribution package) instead of your user directory. If that's the case, then the browser native messaging host config _is_ actually installed in `/usr/lib64/mozilla/native-messaging-hosts/` and we do have to figure out LibreWolf's system paths.

Because the LibreWolf RPM has everything in `/usr/share/librewolf/`, I'm going to assume that's where its `native-messaging-hosts` directory should be as well. So the symlink you'd need is:
```sh
sudo ln -s /usr/lib64/mozilla/native-messaging-hosts /usr/share/librewolf/native-messaging-hosts
```

And there should already be a GSConnect configuration in `/usr/lib64/mozilla/native-messaging-hosts/` that points to the system-installed JavaScript code for the host.

If you're _intending_ to run GSConnect as a user extension (one installed to `$HOME/.local/share/gnome-shell/extensions/`), then you should uninstall the `gnome-shell-extension-gsconnect` RPM from your system, to remove the copy in `/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io` that (based on the deletion of that NMH config file you created) is being used instead. Then the user extension should automatically create the proper file in `$HOME/.mozilla/native-messaging-hosts/` on startup.

**Comment by ferdnyc** [comment]
(I might normally suggest that you could just symlink `/usr/lib64/mozilla/native-messaging-hosts/org.gnome.shell.extensions.gsconnect.json` to your `$HOME/.librewolf/native-messaging-hosts` directory.... Oh! No, wait, actually that would work. Because GSConnect doesn't _know about_ that path, it won't delete the symlink even if it's running as a system extension. So that's another option, if you want to continue using the system-installed GSConnect:

```sh
rm $HOME/.librewolf/native-messaging-hosts
mkdir -p $HOME/.librewolf/native-messaging-hosts
ln -s \
  /usr/lib64/mozilla/native-messaging-hosts/org.gnome.shell.extensions.gsconnect.json  \
  $HOME/.librewolf/native-messaging-hosts/
```
(You have to delete the symlink and create a real directory, because if the librewolf NMH directory is symlinked to Mozilla's and you create a link _there_, system-installed GSConnect **will** still delete it on startup.)

**Comment by MarcoWilli** [comment]
I´m sorry. But I´ve read your replies several times and tried to understand. But atm this is all too confusing for me.
I did what you´ve posted in your latest reply but it does not work. The symlink points to a non existent file. I then checked because of the $home variable but that does get translated correctly so it´s not because of this.

Honestly I even don´t know, if I really need that extension to work but I thought I´d give it a try and as its not working my intention was that there might be someone else having this issue and that´s why I opened this case.

After fiddling around with that all, my keepassxc extension didn´t work so I revoked the changes. But to get it working at beginning I copied over the needed file to the messagin-hosts directory manually. And atm I rather have this one working than fiddling around more. Dunno if this has to do with confusing me maybe, too.

**Comment by ferdnyc** [comment]
@MarcoWilli Understood, sorry we couldn't get it sorted out. Given LibreWolf's focus on security and privacy, it's even entirely possible that it could be blocking something required by GSConnect's browser integration. I think we may just have to declare LibreWolf an unsupported browser, at least for now.
