### ISSUE TITLE
python-nautilus on Ubuntu 22.04 is python3-nautilus

### ISSUE THREAD

**Issue by Cybereu** [GSConnect/gnome-shell-extension-gsconnect#1389]

**Comment by Batwam** [comment]
I noticed that today as well, I believe that the instructions should be updated accordingly. Did you manage to make SFTP Automount work in Nautilus with this package though? nothing is happening in Nautilus when I connect the phone...

**Comment by ferdnyc** [comment]
@Cybereu 
Ugh, on Fedora we fixed the naming back to `nautilus-python`, since the contents of the package are NOT Python code. (It contains a shared library that embeds a Python interpreter into Nautilus. Actually on Debian-derived I'm surprised it's not named something like `libnautiluspython3` or w/e.) Still, if the info in the wiki is wrong feel free to update it, unless there's a permissions issue? (I haven't checked in a while.)

@Batwam 
Automounting probably isn't gonna work, since the Android end won't be listening for a connection until it's told to, and it will drop the connection pretty quickly if it's not used (and sometimes even if it is used). Keeping a persistent mount to a remote filesystem just doesn't seem to be possible with recent Android releases. Using the Mount option in the GSConnect section of the user menu is probably your safest bet.

**Comment by Batwam** [comment]
thanks for the response. I realised later on that the mount option isn't implement/possible for iphone so that wasn't going to work.

Regarding the package name, it looks like it was renamed to python3-nautilus recently as it has that name in Ubuntu 22.04 as well as Debian Stable/Testing/SID so I'll update the Wiki accordingly.

**Comment by andyholmes** [comment]
Closing since I think this has been addressed by updating the Wiki. Thanks for your contribution @Batwam!
