### ISSUE TITLE
Slideshow / Presentation Remote not working

### ISSUE THREAD

**Issue by bevsxyz** [GSConnect/gnome-shell-extension-gsconnect#1406]
> ***ATTENTION**: GSConnect only supports the latest, stable version of GNOME. We are no longer accepting bug reports for previous versions.*

**Describe the bug**

I have been trying to control remotely control slides from the KDEConnect android app. The forward and backward buttons register but do not register any kind of action with Google slides in firefox or Impress for that matter. The pointer button doesn't seem to even respond at all.

**Steps To Reproduce:**

1. Pair with the kdeconnect app
2. Open any slideshow
3. From the slideshow control panel
4. Try to change slides

**Expected behavior**

Easily change the slides

**Screenshots**

If applicable, add screenshots to help explain your problem. You can drag-and-drop or cut-and-paste images directly into this edit window, to include them in your report.

**Support Log**

Please generate a support log ([Instructions](../wiki/Help#generate-support-log)) and paste any messages related to this issue between the two ``` lines below.

```

GSConnect: 50 (user)
GJS:       17200
Session:   wayland
OS:        Fedora Linux 36 (Workstation Edition)
--------------------------------------------------------------------------------
Jul 04 13:01:16 systemd[9800]: dbus-:1.3-org.gnome.TextEditor@10.service: Consumed 4.408s CPU time.
Jul 04 13:01:26 gnome-shell[12614]: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
Jul 04 13:01:32 gsd-media-keys[16114]: Unsupported modifier, resource creation failed.
Jul 04 13:01:32 gsd-media-keys[16114]: XXX: resource creation failed
Jul 04 13:01:39 gnome-shell[12614]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
Jul 04 13:01:39 gnome-shell[12614]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
Jul 04 13:01:39 gnome-shell[12614]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
Jul 04 13:01:39 gnome-shell[12614]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
Jul 04 13:01:39 gnome-shell[12614]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
Jul 04 13:01:39 gnome-shell[12614]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
Jul 04 13:01:39 gnome-shell[12614]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
Jul 04 13:01:39 gnome-shell[12614]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
Jul 04 13:01:39 gnome-shell[12614]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
Jul 04 13:01:39 gnome-shell[12614]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
Jul 04 13:01:39 gnome-shell[12614]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
Jul 04 13:01:39 gnome-shell[12614]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
Jul 04 13:01:39 gnome-shell[12614]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
Jul 04 13:01:39 gnome-shell[12614]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
```

**System Details (please complete the following information):**

 - **GSConnect version:*50*
   - **Installed from:*GNOME Extensions Website*
 - **GNOME/Shell version:*42.2*
 - **Distro/Release:*Fedora 36*
 - **Display Protocol:*Wayland & X11* Tried both but wayland is  the default

**GSConnect environment (if applicable):**

 - **Paired Device(s):**
 - **KDE Connect app version:*1.19.1*
 - **Plugin(s):*Presenter*

**Additional Notes:**

I tried the problem with both wayland and x11 sessions without any difference in the results. The remote input control works in both sessions, but the wayland one was more smooth without any hiccups

**Comment by malaerba** [comment]
Same problem on ubuntu 22.04, but the pointer works. 

KDEconnect 1.19.1 from F-Droid
GSConnect version:50
Installed from:GNOME Extensions Manager

Support Log: 
`
GSConnect: 50 (user)
GJS:       17200
Session:   wayland
OS:        Ubuntu 22.04 LTS
--------------------------------------------------------------------------------
lug 04 10:28:36 kernel: Lockdown: systemd-logind: hibernation is restricted; see man kernel_lockdown.7
lug 04 10:28:40 gjs[9697]: Object .GSConnectPreferencesWindow (0x55fc9826e2b0), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
lug 04 10:28:40 gnome-shell[9697]: == Stack trace for context 0x55fc97ce6180 ==
lug 04 10:28:40 gnome-shell[9697]: #0   55fc97d170d0 i   /home/fabio/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/gsconnect-preferences:61 (342c8cfcc100 @ 94)
lug 04 10:28:40 gnome-shell[9697]: #1   55fc97d17020 i   /home/fabio/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/gsconnect-preferences:115 (342c8cfcc240 @ 622)
lug 04 10:28:40 kernel: gjs[9697]: segfault at 0 ip 00007f7fb9ecd4e4 sp 00007ffef89022f8 error 4 in libgio-2.0.so.0.7200.1[7f7fb9e20000+110000]
lug 04 10:28:40 kernel: Code: e8 61 8f f5 ff 5a 59 5d c3 66 66 2e 0f 1f 84 00 00 00 00 00 66 90 f3 0f 1e fa 48 8b 07 ff a0 88 00 00 00 0f 1f 00 f3 0f 1e fa <48> 8b 07 ff a0 90 00 00 00 0f 1f 00 f3 0f 1e fa 48 8b 07 ff a0 a0
lug 04 10:28:41 systemd[2175]: Starting Notification regarding a crash report...
lug 04 10:28:41 systemd[1]: Started crash report submission.
lug 04 10:28:41 update-notifier-crash[10073]: /usr/bin/whoopsie
lug 04 10:28:41 whoopsie[10072]: [10:28:41] Using lock path: /var/lock/whoopsie/lock
lug 04 10:28:41 systemd[1]: whoopsie.service: Deactivated successfully.
lug 04 10:28:42 systemd[2175]: Finished Notification regarding a crash report.
lug 04 10:28:42 systemd[2175]: Starting Notification regarding a crash report...
lug 04 10:28:42 systemd[1]: Started crash report submission.
lug 04 10:28:42 update-notifier-crash[10081]: /usr/bin/whoopsie
lug 04 10:28:42 whoopsie[10080]: [10:28:42] Using lock path: /var/lock/whoopsie/lock
lug 04 10:28:42 systemd[1]: whoopsie.service: Deactivated successfully.
lug 04 10:28:42 update-notifier-crash[10083]: gjs-console
lug 04 10:28:43 systemd[1]: Started crash report submission.
lug 04 10:28:43 whoopsie[10095]: [10:28:43] Using lock path: /var/lock/whoopsie/lock
lug 04 10:28:43 systemd[1]: whoopsie.service: Deactivated successfully.
lug 04 10:28:44 systemd[2175]: Finished Notification regarding a crash report.
lug 04 10:28:47 kernel: Lockdown: systemd-logind: hibernation is restricted; see man kernel_lockdown.7
lug 04 10:28:49 dbus-daemon[845]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.216' (uid=1000 pid=10111 comm="gjs /home/fabio/.local/share/gnome-shell/extension" label="unconfined")
lug 04 10:28:49 systemd[1]: Starting Hostname Service...
lug 04 10:28:50 dbus-daemon[845]: [system] Successfully activated service 'org.freedesktop.hostname1'
lug 04 10:28:50 systemd[1]: Started Hostname Service.
lug 04 10:28:52 rtkit-daemon[1204]: Supervising 11 threads of 5 processes of 1 users.
lug 04 10:28:52 rtkit-daemon[1204]: Supervising 11 threads of 5 processes of 1 users.
lug 04 10:28:52 rtkit-daemon[1204]: Supervising 11 threads of 5 processes of 1 users.
lug 04 10:28:52 rtkit-daemon[1204]: Supervising 11 threads of 5 processes of 1 users.
lug 04 10:28:52 rtkit-daemon[1204]: Supervising 11 threads of 5 processes of 1 users.
lug 04 10:28:52 rtkit-daemon[1204]: Supervising 11 threads of 5 processes of 1 users.`

**Comment by bevsxyz** [comment]
@malaerba are you in X11?

**Comment by bevsxyz** [comment]
@malaerba, I just realized that the pointer is supposed to be a mini mouse control 🥲. But it's a shitty mouse with weird scrolling. The clicks are disabled because it's a pointer, but the thing does not emulate a pointer because of the lousy navigation. Remote input is way smoother than that—my logs for this behavior.

```
GSConnect: 50 (user)
GJS:       17200
Session:   wayland
OS:        Fedora Linux 36 (Workstation Edition)
--------------------------------------------------------------------------------
Jul 05 01:13:00 audit: BPF prog-id=83 op=LOAD
Jul 05 01:13:00 audit: BPF prog-id=84 op=LOAD
Jul 05 01:13:00 systemd[1]: Starting systemd-hostnamed.service - Hostname Service...
Jul 05 01:13:00 systemd[1]: Started systemd-hostnamed.service - Hostname Service.
Jul 05 01:13:00 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jul 05 01:13:11 org.gnome.Shell.Extensions.GSConnect[2450]: [/service/device.js:_readLoop:341]: CLOY: {
                                                              "id": 1656963237604,
                                                              "type": "kdeconnect.connectivity_report",
                                                              "body": {
                                                                "signalStrengths": {
                                                                  "1": {
                                                                    "networkType": "LTE",
                                                                    "signalStrength": 2
                                                                  },
                                                                  "2": {
                                                                    "networkType": "Unknown",
                                                                    "signalStrength": 4
                                                                  }
                                                                }
                                                              }
                                                            }
Jul 05 01:13:11 gnome-shell[2062]: libinput error: event9  - CUST0001:00 06CB:CDAA Touchpad: kernel bug: Touch jump detected and discarded.
Jul 05 01:13:11 gnome-shell[2062]: See https://wayland.freedesktop.org/libinput/doc/1.21.0/touchpad-jumping-cursors.html for details
Jul 05 01:13:11 org.gnome.Shell.Extensions.GSConnect[2450]: [/service/device.js:_readLoop:341]: CLOY: {
                                                              "id": 1656963237604,
                                                              "type": "kdeconnect.connectivity_report",
                                                              "body": {
                                                                "signalStrengths": {
                                                                  "1": {
                                                                    "networkType": "LTE",
                                                                    "signalStrength": 2
                                                                  },
                                                                  "2": {
                                                                    "networkType": "Unknown",
                                                                    "signalStrength": 4
                                                                  }
                                                                }
                                                              }
                                                            }
```

The next/prev did not work again. Also, for some reason, my phone disconnected right after I tried this and would not reconnect, even though both the devices are on the same network. The logs now--

```

GSConnect: 50 (user)
GJS:       17200
Session:   wayland
OS:        Fedora Linux 36 (Workstation Edition)
--------------------------------------------------------------------------------
Jul 05 01:24:02 gsd-media-keys[2784]: Unsupported modifier, resource creation failed.
Jul 05 01:24:02 gsd-media-keys[2784]: XXX: resource creation failed
Jul 05 01:24:03 gsd-media-keys[2784]: Unsupported modifier, resource creation failed.
Jul 05 01:24:03 gsd-media-keys[2784]: XXX: resource creation failed
Jul 05 01:24:04 gsd-media-keys[2784]: Unsupported modifier, resource creation failed.
Jul 05 01:24:04 gsd-media-keys[2784]: XXX: resource creation failed
Jul 05 01:24:06 gsd-media-keys[2784]: Unsupported modifier, resource creation failed.
Jul 05 01:24:06 gsd-media-keys[2784]: XXX: resource creation failed
Jul 05 01:24:06 gsd-media-keys[2784]: Unsupported modifier, resource creation failed.
Jul 05 01:24:06 gsd-media-keys[2784]: XXX: resource creation failed
Jul 05 01:24:07 gsd-media-keys[2784]: Unsupported modifier, resource creation failed.
Jul 05 01:24:07 gsd-media-keys[2784]: XXX: resource creation failed
Jul 05 01:24:08 gsd-media-keys[2784]: Unsupported modifier, resource creation failed.
Jul 05 01:24:08 gsd-media-keys[2784]: XXX: resource creation failed
Jul 05 01:24:09 gsd-media-keys[2784]: Unsupported modifier, resource creation failed.
Jul 05 01:24:09 gsd-media-keys[2784]: XXX: resource creation failed
Jul 05 01:24:09 gsd-media-keys[2784]: Unsupported modifier, resource creation failed.
Jul 05 01:24:09 gsd-media-keys[2784]: XXX: resource creation failed
Jul 05 01:24:12 gsd-media-keys[2784]: Unsupported modifier, resource creation failed.
Jul 05 01:24:12 gsd-media-keys[2784]: XXX: resource creation failed
Jul 05 01:24:14 systemd[1734]: dbus-:1.2-org.gnome.TextEditor@0.service: Consumed 7.174s CPU time.
```

**Comment by bevsxyz** [comment]
Perhaps I should create a new issue, but the freedesktop link for touchpad jump errors doesn't work for the version mentioned in the log. The latest developmental version is available at https://wayland.freedesktop.org/libinput/doc/latest/touchpad-jumping-cursors.html

**Comment by bevsxyz** [comment]
> @malaerba, I just realized that the pointer is supposed to be a mini mouse control smiling_face_with_tear. But it's a shitty mouse with weird scrolling. The clicks are disabled because it's a pointer, but the thing does not emulate a pointer because of the lousy navigation. Remote input is way smoother than that—my logs for this behavior.

Uh oh, that's not how it is supposed to work.

> It is possible to control presentations using the previous/next slide button. When the device is locked, you can use the volume up/down button to do that. You can also highlight something using the laserpointer. Just move your phone and the blue circle will follow! Using the hamburger menu, you can toggle fullscreen (F5) or quit the presentation (Esc).

https://userbase.kde.org/KDEConnect#Presentation_control

Also the toggle fullscreen or quit presentation options doesn't work either.

**Comment by malaerba** [comment]
> @malaerba are you in X11?
> 

No, Wayland. 

> Also the toggle fullscreen or quit presentation options doesn't work either.
> 

The same for me.

There is a version of GSConnect in the ubuntu repository. I can try to install it and check if it works, but last time I tried it it didn't work at all.

**Comment by bevsxyz** [comment]
> There is a version of GSConnect in the ubuntu repository. I can try to install it and check if it works, but last time I tried it it didn't work at all.

There's one in fedora too. But for some reason the extensions in the system path is not recognised. I didn't bother troubleshooting because we can install directly from the gnome website as user.

**Comment by bevsxyz** [comment]
As @adam-hussain noted in PR #1409 and I confirmed, building from the repo fixes all the issues with the presenter except the pointer usability.

It can be done following the instructions at https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Installation#install-from-git

>```bash
>git clone https://github.com/andyholmes/gnome-shell-extension-gsconnect.git
>cd gnome-shell-extension-gsconnect/
>meson _build .
>ninja -C _build install-zip
>```

Well, don't forget to install meson first!

**Comment by bevsxyz** [comment]
Closing the issue since the issue is solved. Well the packaging updates are still pending. That's for another issue.

**Comment by ferdnyc** [comment]
I tested Pointer mode just now, in fact with the GSConnect 50 build in Fedora's package collection (on F36), and it works fine.

The interface is a little unintuitive, and until you realize how it works, it can be confusing. At first I thought dragging my finger around on the "Pointer" button moved the mouse, but actually touch gestures do nothing and the bits of motion I was seeing were just accidental inputs.

The way it _actually_ works is: Whenever you hold your finger down on the "Pointer" button, the phone's gyroscopic motion sensors get translated into mouse movements. So, you can wave your phone around in the air in front of you, and any up/down/left/right motions you make, the pointer will follow those gestures.

It's best to take your finger OFF the "Pointer" button as soon as you stop moving, because when Pointer input is activated the mouse will tend to drift a little even if you're holding the phone still. But with a little practice, it's easy to get in the habit of quickly pressing Pointer, waving the mouse pointer over to where you want it, then lifting your finger so it stops moving wherever you want it. It's actually kind of a cool way to move the mouse around, though I can't imagine how it would be useful in any setting OTHER than a presentation.

**Comment by ferdnyc** [comment]
(The "blue circle" mentioned in the KDE docs is a feature of KDE's presentation software, not of KDE Connect / GSConnect, so in any other context you'll just be moving the regular mouse pointer instead. But it does work, at least in Wayland.)

**Comment by Khyta** [comment]
I have downloaded the latest release using Gnome's [Extension Manager](https://itsfoss.com/extension-manager/) because the snap Firefox version won't let you install it.

The problem is that Sldieshow remote controls still do not work.

GSConnect Version: 50
Ubuntu Version: 22.04.1 LTS x86_64
Kernel: 5.15.0-48-generic
DE: GNOME 42.4

**Comment by pfuhlert** [comment]
Is there any update? Volume buttons as prev/next would be very nice to have on Ubuntu 23.04

**Comment by molavi25** [comment]
Slideshow remote controls doesn't work.
