### ISSUE TITLE
Keyboard And Mouse Integration

### ISSUE THREAD

**Issue by scientiac** [GSConnect/gnome-shell-extension-gsconnect#1458]
Right now the keyboard and mouse integration from kde connect is not that great. it does work and I use my phone on a tripod and type from laptop, but i have to invoke the typing field manually and there is no mouse integration as I can see in GS connect to use that to invoke the keyboard on kde connect. 

Features/Implementation: [Consider this a mockup but in text.]

[When only one device is connected of course.]
1. When Enabled, the mouse should be activated on mobile from the edge that the mouse pointer went through the laptop. (similar to how mouse passes through in a dual monitor condition) [disabling mouse pointer on shell and enabling on mobile and vice versa for connection ]
2. Keyboard should be reserved for phone when the pointer is on the phone.
3. Ability to hold and drag to the edge of screen to get a prompt to share that file to the connected device.

I know this is a lot, but it seems doable on existing kdeconnect protocols. Hope this could be done.

And very much thanks to this project, it's super awesome.

**Comment by ferdnyc** [comment]
@scientiac 

Basically, it sounds like you're requesting [Synergy](https://symless.com/synergy), but expanded to include Android devices? (At least from a look-and-feel perspective?)

It's an interesting idea, though I'm not sure it IS implementable with the current protocols — and more importantly, under the current Android security model(s). Having a non-system app send input events while it's not running in the foreground is the kind of thing Android releases have been locking down heavily since Android 9/10.

That sort of feature would likely be blocked at the system level for the same sort of reasons clipboard sharing can no longer function silently in the background: As convenient as it would be to have the device's clipboard automatically cloned to a paired PC, it's also a massive security risk if any random app (which is exactly what KDE Connect is, from the Android OS perspective) is able to spirit away every piece of text copied on the device. Especially considering how frequently people tend to copy-paste things like passwords, credit card numbers, etc... If KDE Connect can do it, then so can the random malware hiding in a downloaded game or toy app, except **that** app sends all of your clipboard texts to a random server in a foreign country.

By the same token, if the KDE Connect app isn't running in the foreground, having it generate user input events to the Android system interface / other app interfaces would certainly be _convenient_, but it'd also be fertile ground for malware to perform all manner of shady actions.

(For example, imagine if an app containing malware detects that Google Play just created a malware alert notification _for that app_, and immediately generates the necessary input events to dismiss it without the user ever knowing it was there.)

Heck, Synergy itself doesn't even work on _**Linux**_ anymore unless the system is running X11. The featureset it provides is pretty reliant on X protocol insecurities. Wayland, like Android, won't casually accept fake input events / entire fake input devices injected by any random executable running behind-the-scenes with no visible GUI of its own.

**Comment by scientiac** [comment]
Thanks @ferdnyc for the explanation. This issues is better off closed I assume.

**Comment by ferdnyc** [comment]
@scientiac Unfortunately, probably yeah.

Should someone have a clever explanation for why I'm wrong (I'm always happy to be wrong, especially about something I think _can't_ be done), project members can always reopen this, and anyone else is invited to create a new issue. **#TellMeWhyImWrong!**
