### ISSUE TITLE
Add ArchLinux support of gvc-1.0.typelib

### ISSUE THREAD

**Issue by FrankVan1982** [GSConnect/gnome-shell-extension-gsconnect#1484]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**System Details (please complete the following information):**
 - GSConnect version: [e.g. 16, 15, ... (displayed in the GSConnect "About" window)]
   - Installed from: [e.g. extensions.gnome.org, GitHub Release download, distro package, ...]

**Additional context**
Add any other context for your suggestion here, including screenshots if applicable.

#### Please delete this line and everything below before submitting your request

GSConnect works in concert with the [KDE Connect][1] app on paired Android devices. Communication between GSConnect and the device is controlled by **KDE Connect**, _not_ GSConnect.

Any request that would require features not supported in KDE Connect, or would require GSConnect to deviate from the KDE Connect protocols, cannot be implemented. Any such requests should be made to the KDE Connect project. The requested functionality can only be implemented in GSConnect after support is added to KDE Connect.

[1]: (https://community.kde.org/KDEConnect)

**Comment by ferdnyc** [comment]
@FrankVan1982 

Gvc is the GNOME audio mixer interface (GNOME Volume Control), but I'm not clear on how you'd like that supported in GSConnect.

Could you provide a bit more detail for your request? (Keeping in mind the note in the report form regarding the KDE Connect protocol restrictions.)

For example, if you're looking to use the KDE Connect Android app to control your PipeWire system mixer via Gvc, that's probably never going to happen because the KDE Android app isn't likely to ever support Gvc.

KDE Connect Android and GSConnect already support MPRIS2 media player control, including volume adjustment, as it represents a cross-desktop protocol that both the KDE and GNOME sides can implement.

I'm going to close this as lacking any clear request for an implementable feature, but feel free to reopen it with additional details if you're requesting something we can support.
