### ISSUE TITLE
Gnome 43. Remote mouse input lags

### ISSUE THREAD

**Issue by githubVladimirT** [GSConnect/gnome-shell-extension-gsconnect#1503]
On gnome 43 remote mouse input lags (mouse speed is very slowly).
Сhanging the speed indicator on the phone does not affect anything.

How to resolve this problem?

**Comment by ferdnyc** [comment]
@githubVladimirT 

I can't seem to reproduce. I tried on my Android 12 phone, paired to both my F36 desktop and my F37 laptop. (GNOME 42 and 43, respectively, and both using Wayland) Remote mouse input felt similar on both. Perhaps a bit jerkier with the laptop, but I'm willing to blame its very old, low-bandwidth wireless card for that (vs. my desktop with gigabit ethernet).

What's more, changing the Remote Input plugin "Set touchpad sensitivity" and "Set pointer acceleration" values in KDE Connect definitely altered the pointer responsiveness on both target machines.

...Do you happen to have a HiDPI (scaled) screen, on whatever device you're sending input to? I **don't**, so that could be one possible explanation for the different behavior we're seeing. 

Looking at a Generate Support Log capture of a mouse input session, it looks like the movements KDE Connect sends are in raw pixel units, each `mousepad.request` packet contains pointer-position `dx` and `dy` delta values. What's more, much of the time the capture is fast enough that packets frequently come through containing very small values like `"dx": 0, "dy": -1` or `"dx":1, "dy": 2`.

Screen scaling could be further constraining those values, _theoretically_. (That's just a shot-in-the-dark theory.)

**Comment by darkdragon-001** [comment]
I tested on Ubuntu 22.10 with Gnome 43 and for me it works well. I had to play a little with "Set touchpad sensitivity" and "Set pointer acceleration" settings for it to feel natural for me though.

**Comment by ferdnyc** [comment]
No response from the original reporter, and with both myself and @darkdragon-001 reporting we're unable to reproduce the problem, I'm going to close this. But feel free to file a new issue, @githubVladimirT — or anyone else — if you still encounter this problem.

**Comment by bdbdgittyhubby** [comment]
Unfortunatelly I have the same problem. Sometimes it works without the mouse lagging, But most of the time the mouse seems to lag. I don't know if it have something to do with "mouse.requests" which device is logging or something else..

**Comment by githubVladimirT** [comment]
If you set the "mouse acceleration" value to "disabled", the pointer movement will become almost smooth.
However, there is still some pointer jumping.

I'll try to experiment some more, if I find a solution, I'll write below.

___
Fedora 40
Gnome 46.5

Android 14

**Comment by bdbdgittyhubby** [comment]
> If you set the "mouse acceleration" value to "disabled", the pointer movement will become almost smooth. However, there is still some pointer jumping.
> 
> I'll try to experiment some more, if I find a solution, I'll write below.
> 
> Fedora 40 Gnome 46.5
> 
> Android 14
Thanks man!
