### ISSUE TITLE
GSconnect vulnerable to man-in-the-middle attack due to compatibility

### ISSUE THREAD

**Issue by nuschpl** [GSConnect/gnome-shell-extension-gsconnect#1606]
### Describe the bug

The following bug states some problem:
https://github.com/GSConnect/gnome-shell-extension-gsconnect/issues/930
and it seems it's the reason to undermine all users security is that some  users are experienciing issues with legacy devices. And by those are users who didn't update software in their phones since years 
This is by the line:
```
// Allow TLSv1.0 certificates
// See https://github.com/GSConnect/gnome-shell-extension-gsconnect/issues/930
imports.gi.GLib.setenv('G_TLS_GNUTLS_PRIORITY', 'NORMAL:%COMPAT:+VERS-TLS1.0', true
```
in:
> /$HOME/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js

### Expected behavior

There should be an option to adjust TLS options but compromising security of service which is exposed on all interfaces(listen 0.0.0.0) should never be default setting

### GSConnect version

50

### Installed from

GNOME Extensions website

**Comment by ferdnyc** [comment]
I certainly have no issues with dropping support for Android versions that're _that_ ancient, at this point. Almost 3 years ago (the era that bug exists in), it was common for users to still be running Android 4/5/6. But _**today**_... well, if there are any still out there, not being able to pair their device via KDE Connect is probably the _least_ of the problems they have to deal with.

(Plus, the KDEConnect MR that brought in that linked commit establishes the oldest-supported release on their side — Android 5; IMHO still way too far back, but whatev — which is therefore the minimum we can expect to see the Android app still running on. And even Android 5 apparently doesn't require TLS 1.0. Sounds like that silliness died with Android 4.4.)

**Comment by andyholmes** [comment]
Yeah, KDE Connect has a (I think) good policy of trying to keep older devices working longer, but that has obvious downsides (as we've also seen with the SFTP plugin). I think most Android 4.4 devices are probably nearing life expectancy of the hardware, or been updated to a newer ROM.

Worth pointing out that this will really not help all that much with MITM attacks though :)

**Comment by ferdnyc** [comment]
> Worth pointing out that this will really not help all that much with MITM attacks though :)

Indeed — [RFC7457](https://www.rfc-editor.org/info/rfc7457) is the canonical survey of TLS vulnerabilities. The significant ones present in TLS 1.0/1.1 (the ones that aren't _shared_ by later TLS revisions, anyway) are overwhelmingly traffic-decryption compromises, executed by exploiting various timing or pattern-predictability weaknesses in the session encryption.

A (small) relief _there_ is that those sort of exploits require that a session be **using** TLS 1.0 or 1.1 before it becomes vulnerable. If all of your endpoints support TLS 1.2/1.3, and they always establish connections using the more recent versions, then merely having TLS 1.0/1.1 _enabled_ on the server doesn't significantly impact the security of those later-TLS sessions.

OTOH, if you **do** get MitM'd, the bad actor is now in a position to do things like meddle with the protocol negotiation, possibly in order to trick your more-secure devices into establishing connections using less-secure TLS levels. And then those decryption attack vectors open right back up.

So, yeah, no argument: Best if they're just disabled completely, whenever possible.
