### ISSUE TITLE
"Keep Alive" option isn't very clear

### ISSUE THREAD

**Issue by automerisnaranja** [GSConnect/gnome-shell-extension-gsconnect#1613]
### Describe the bug

In GSConnect settings, there is a option called "Keep Alive" with the title "Behavior when locked". However, these strings aren't very clear. What will be kept alive, KDE Connect or GSConnect or both? And what "alive" means? Does "locked" apply for the phone or for the desktop/notebook? 

### Steps to reproduce
Pair a device and then go open the "Mobile Settings" item from GSConnect submenu from quick settings.

### GSConnect version

55

### Installed from

GNOME Extensions website

### GNOME Shell version

gnome-shell-44.0-4.fc38.x86_64

### Linux distribution/release

Fedora 38

### Paired device(s)

S20 FE

### KDE Connect app version

1.24.3

### Screenshots

![Screenshot from 2023-04-25 17-43-04](https://user-images.githubusercontent.com/127631126/234399024-9a31f96b-58e3-4a9e-9c0e-1c477a4722da.png)

**Comment by ferdnyc** [comment]
Fair enough. I think the intent of placing that setting on the _root_ screen of the Mobile Settings interface was that it would help make some of those answers implicit. (Because it's not a device preference, it's nothing to do with the Android side of things, only the local GNOME Shell lock screen.)

Past that, it's probably _fairly_ clear what the switch does... _**assuming**_ the user knows that GNOME Shell normally disables extensions when its lockscreen activates. But that's a sausage-making detail that's far from common or expected knowledge. And without that detail, the labels aren't nearly as descriptive as they might seem to anyone who _does_ know.

(Plus, we've got the width of the entire window to work with. There's room for an entire sentence there, so "Keep Alive" seems more than a bit terse.)

**Comment by ferdnyc** [comment]
@mspatil32 @automerisnaranja Does this seem sufficiently clear?

![image](https://user-images.githubusercontent.com/538020/235294631-6aa881c3-c70d-48b6-8c7f-6787ee470c74.png)

**Comment by automerisnaranja** [comment]
> @mspatil32 @automerisnaranja Does this seem sufficiently clear?
> 
> ![image](https://user-images.githubusercontent.com/538020/235294631-6aa881c3-c70d-48b6-8c7f-6787ee470c74.png)

Yes! :D Sorry for the late response.

**Comment by automerisnaranja** [comment]
> > @mspatil32 @automerisnaranja Does this seem sufficiently clear?
> > ![image](https://user-images.githubusercontent.com/538020/235294631-6aa881c3-c70d-48b6-8c7f-6787ee470c74.png)
> 
> Yes! :D Sorry for the late response.

I would suggestion "Keep GSConnect active when GNOME Shell is locked", since options are usually phrased in this way. I can propose a merge request, if you aprove this.

**Comment by ferdnyc** [comment]
@automerisnaranja Sure, I have no real preference. Except to note that **any** change makes work for our translators, so let's try to make this the last tweak to that particular string.

(If you do submit a PR, the translation master will also need to be updated... but as long as you leave the box checked to allow maintainer edits, I can push a commit to your PR branch to handle that side of things.)

**Comment by automerisnaranja** [comment]
> @automerisnaranja Sure, I have no real preference. Except to note that **any** change makes work for our translators, so let's try to make this the last tweak to that particular string.
> 
> (If you do submit a PR, the translation master will also need to be updated... but as long as you leave the box checked to allow maintainer edits, I can push a commit to your PR branch to handle that side of things.)

Ok, thanks a lot! Here it is: https://github.com/GSConnect/gnome-shell-extension-gsconnect/pull/1632

Hey, I kinda... made a mess when committing because of this damn short attention. Hopefully this won't cause any confusion.
