### ISSUE TITLE
Translation files have wrong names

### ISSUE THREAD

**Issue by piotrdrag** [GSConnect/gnome-shell-extension-gsconnect#1620]
### Describe the bug

Many translations are duplicated or have an unnecessary country tag which limits their use, e.g. `ar_SA.po` won’t be used when the system locale is `ar_KW`. To make the most out of the translations you have and comply with other projects (like [GNOME Shell](https://gitlab.gnome.org/GNOME/gnome-shell/-/tree/main/po)), here are the changes you should make:

`ar.po` and `ar_SA.po` → `ar.po`,

`fa-IR.po`, `fa_IR.po` and `fa.po` → `fa.po`, 

`fi_FI.po` and `fi.po` → `fi.po`,

`fy-NL.po` and `fy_NL.po` → `fy.po`,

`id-ID.po` and `id_ID.po` → `id.po`,

`ko-KR.po`, `ko_KR.po` and `ko.po` → `ko.po`,

`nl_BE.po` and `nl_NL.po` → `nl.po`,

`pt_PT.po` → `pt.po` (BUT `pt_BR.po` should stay as-is),

`sr_CS.po` and `sr@latin.po` → `sr@latin.po`,

`sv.po`, `sv-SE.po` and `sv_SE.po` → `sv.po`.

### GSConnect version

Newest git

### Installed from

GitHub releases (zip file)

**Comment by ferdnyc** [comment]
@piotrdrag 

Thanks for bringing this up. \*sigh\* Now let me refresh my memory of why things are the screwy way they are... ... ...

Right, OK. So, there are a few issues at play here:

1. Ultimately and in practice, Crowdin ends up driving our language file naming, because new translations invariably end up getting created _there_ before getting merged into the repo.
2. We've changed our Crowdin configuration a few times, as we've attempted to dial this in. That's why there are so many redundant filenames — if you check the _dates_ on those files, you'll find that some are vestigial and not really updating anymore. (Mostly, the `xx-YY.po` filenames are leftovers from the previous Crowdin configuration, which was automatically creating files with those names. Because we never really _want_ files named that way, in 639641f1 I changed the configuration so that it would at least create files with `xx_YY.po` names, instead. The `xx-YY.po` files can in theory be deleted, as Crowdin should hopefully no longer have any interest in those files.
3. However, as you point out, mostly we want to be using translation file names without any regional specifier, named simply `xx.po`. To get Crowdin using _those_ names, every time a `xx_YY.po` file is added for a new country, a mapping needs to be added to the `crowdin.yml` file instructing it that `xx_YY.po` should be stored as `xx.po` instead. Languages we either missed or have added more recently are the ones that lack a mapping to `xx.po`.

#### (Fortunately) not a problem, merely clutter

I can certainly delete the `xx-YY.po` files, hopefully at this point Crowdin should ignore them entirely, and in every case they're less recent than the corresponding `xx_YY.po` by three months. (IOW, since I made that config change. Which was the intent and a good sign that it was successful.) But none of those files are packaged by `meson` anyway (one of the reasons for changing the config), so really they're nothing more that repo clutter that has no effect on the packaged extension.

#### Very real problem 1

..That brings us to the `xx_YY.po` files. _For the most part_, where there are both `xx.po` and `xx_YY.po` files the `xx_YY.po` file is the one being updated by Crowdin, and the `xx.po` file is "vestigial". `sv.po`, for example, contains only a _single_ translated string. (That's according to the `file` command, when run on the resulting `.mo` file. And actually I think it's overestimating by 1 or can't comprehend a file with 0 messages, because I can't find any translated strings in that file at all.) Whereas `sv_SE.po` contains 254 Swedish message translations.

HOWEVER! The _very, very_ unfortunate thing about that situation, I now see, is that while Meson is properly packaging Swedish translations into `locale/sv/LC_MESSAGES/org.gnome.Shell.extensions.GSConnect.mo`, it's using the **`sv.po`** file as the source for those translations, rather than the `sv_SE.po` file. Meaning, our packaged Swedish localization consists of zero translated messages, even though the Swedish translations in Crowdin are 93% complete!) It appears as though `fa`, `fi`, and `ar` may also be affected in the same way.

So, obviously that's a real problem.

#### Very real problem 2

There's also another group of translations we're simply not packaging **at all**, apparently because they aren't included in the `po/LINGUAS` file that defines the set of input locales for the translation compiler. That seems to cover both `ko`, on the has-a-`xx.po`-file front, as well as all of the locales where the only files present are `xx_YY.po` / `xx-YY.po` files other than `zh_*.po` (which are both packaged as-is, correctly) and `nl_*.po`/`pt_*.po` (where both are packaged, apparently-incorrectly?)

So, I'll _first_ work (because it's easier) on getting `ko` and the newer languages — hopefully that's just `fy` and `id`, looks like — into the configuration, so that they'll start being included in the extension builds. (After mapping them from `ko_KR.po`, `fy_NL.po`, and `id_ID.po` to `ko.po`, `fy.po`, and `id.po`, respectively).

**Comment by ferdnyc** [comment]
> 3\. To get Crowdin using _those_ names, every time a `xx_YY.po` file is added for a new country, a mapping needs to be added to the `crowdin.yml` file instructing it that `xx_YY.po` should be stored as `xx.po` instead. Languages we either missed or have added more recently are the ones that lack a mapping to `xx.po`.

I _suspect_ that part is only true because our Crowdin configuration is **wrong**, and #1622 contains an attempt at fixing it to what I'm becoming convinced is the _actual_ correct configuration, which (if I'm right) shouldn't require us to intervene at all for the majority of new language additions. Only in the rare cases where the filename _shouldn't_ be simply `xx.po`.

#### Very real (but language-specific) problem 3

While examining the `.po` files in the course of cleaning them up, I _also_ noticed that our `sr@latin.po` file contains an eclectic mix of latin and cyrillic script. I'm not even sure if that's our fault or the translators', but it's not great either way. At least `sr.po` seems to be 100% cyrillic, AFAICT.
