### ISSUE TITLE
Notification of received file lacks open buttons once toast is hidden

### ISSUE THREAD

**Issue by eliotb** [GSConnect/gnome-shell-extension-gsconnect#1747]
### Describe your request

When a file is received on the desktop from the phone, a  **Transfer Successful** notification 'toast' pops down with the file name. If the mouse is hovered over this,  two buttons "Open Folder" and "Open File" appear.  

However, this notification very quickly (1-2 sec) disappears from view, into the stack of notifications that I can see by clicking the Date/Time in the top bar. Once it is in that list, it no longer has the two Open buttons, and all that can be done is dismiss the notification.

It would be nice if the stacked notification also had the Open buttons.

Note: this is related to #1743 in that it is about getting easier access to received files.

### Proposed solution

It would be nice if the stacked notification also had the Open buttons.

### GSConnect version

54

### Installed from

GNOME Extensions website

### GNOME Shell version

43.9

### Linux distribution/release

Debian 12

**Comment by andyholmes** [comment]
Sorry, but GSConnect does not control the notification system. There is ongoing work in GNOME Shell that will hopefully improve this, but GSConnect can't take responsibility for re-writing the notification system from the inside-out to handle this case.

**Comment by eliotb** [comment]
Checking in here for other reasons, I noticed that the behaviour I was requesting appears in the video in #1810 
It looks like Gnome 46 has added this feature:

> Enhanced notifications: with improved layouts, and a new header in each notification to show which app sent it. It is now also possible to expand notifications in the list, in order to use notification actions at a time that suits you.

**Comment by ferdnyc** [comment]
Indeed. Persistent action buttons are something I've [been agitating for](https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/2981#note_1912567), so thankfully it's _finally_ fixed.

Where GSConnect sets action buttons, they can now be accessed from the notification list instead of being a "blink-and-you-miss-it" thing with the popup notification.

![Screenshot from 2024-05-23 10-18-22](https://github.com/GSConnect/gnome-shell-extension-gsconnect/assets/538020/0842fb2d-e68b-49dc-902d-84e2f730054b)

(Note the "Reminders" buttons on my GSConnect alarm notifications. Which wouldn't actually do anything because they're action buttons from my phone, but the point is they're there.)

So once you upgrade to GNOME 46, this will be solved.
