### ISSUE TITLE
Gnome 46 support

### ISSUE THREAD

**Issue by aknarts** [GSConnect/gnome-shell-extension-gsconnect#1764]
### Describe the bug

With the update of the gnome-shell the extension broke. So far I have found that `MessageTray.NotificationBanner` got removed here https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/3173 not sure yet what the replacement is or I would fix it myself.

### GSConnect version

56

### Installed from

GNOME Extensions website

### GNOME Shell version

46

### Linux distribution/release

Arch Linux

**Comment by aknarts** [comment]
I see there is an assumption that everything works #1740 :)

**Comment by Skythrew** [comment]
Same issue here on Arch, I'm investigating on the issue.

**Comment by vinylSummer** [comment]
The extension broke for me too on Arch with gnome 46. After `gsettings set org.gnome.shell disable-extension-version-validation true` the error is TypeError: class heritage MessageTray.NotificationBanner is not an object or null.

**Comment by Neo-29** [comment]
Can confirm it's broken here on gnome 46

**Comment by andyholmes** [comment]
Unless there is an additional issue to report here, this is a duplicate of #1762.

> I see there is an assumption that everything works https://github.com/GSConnect/gnome-shell-extension-gsconnect/pull/1740 :)

Yes, this was likely tested during the release-candidate, or possibly just with a stale version before the relevant change landed.

**Comment by Skythrew** [comment]
Seems like the only part of the extension not working is the notification part, causing it to crash. Indeed, as OP said `MessageTray.NotificationBanner`, which was used for notifications, got removed and should be replaced (as it is written in the commit message by GNOME) by `Calendar.NotificationMessage`. Thus, in order to have the extension working again, we have to reimplement the notification part with this new class.

**Comment by Neo-29** [comment]
I disagree.
Here NOTHING works on arch.

**Comment by Skythrew** [comment]
Nothing works because the notification part makes the whole extension crash. If you try to debug it and reinstall the extension, just by changing `MessageTray.NotificationBanner` to `Calendar.NotificationMessage`, the only part of the extension not working will be notifications, the rest will work correctly.

**Comment by Neo-29** [comment]
I don't even have the button in gnome settings o' the right.
I shall wait for a fix
Not a problem

**Comment by Skythrew** [comment]
The fix proposed in #1767 is not complete. It only allows the extension to work correctly without the notification part working. The notification part needs a reimplementation with the new `Calendar.NotificationMessage` that I'm currently working on because otherwise, the extension will "crash" on each notification that should be received.
