### ISSUE TITLE
Telephone Audio?

### ISSUE THREAD

**Issue by ThePowerTool** [GSConnect/gnome-shell-extension-gsconnect#1835]
### Describe the bug

I started using Gnome with KDE Connect a few years ago and love it.  I installed it and immediately started using SMS and Telephony-audio on my desktop.  It has been some time but I attempted to pick-back-up where I left-off and while I can see I am "connected" from my computer and phone:

Problem:  Telephone audio is now unavailable via my desktop.

I have gone through all the information I could find on the app and while I can verify other functions seem to be working I just can't get my phone audio back to the headset connected to my desktop.

Is this even the correct place to ask?

Any help, or even pointers, would be sincerely appreciated.

I am running Fedora 40
:~$ rpm -qa | grep -i gnome-desktop
gnome-desktop3-44.0-15.fc40.x86_64
gnome-desktop4-44.0-15.fc40.x86_64

Pixel 6
Android 14

Thank you very much, in advance!

### Steps to reproduce

I do not know.  I reconnected my phone KDE connect to my desktop GS Connect after some time (maybe a year) and telephone audio isn't working.

I do hear the beep when I press to hang-up the call.  It is difficult to hear.

### Expected behavior

When computer and device are "connected" telephone audio becomes available via headset connected to PC computer.

### GSConnect version

57

### Installed from

OS package manager

### GNOME Shell version

44.0

### Linux distribution/release

Fedora 40

### Paired device(s)

Pixel 6

### KDE Connect app version

1.31.1

### Support log

```plain text
I tried but the dialog didn't fill and the review log button didn't launch my editor.
```

**Comment by ThePowerTool** [comment]
Update:  I spent a lot of time, yesterday, going through all the settings on my Pixel 6.  I accepted a "security update" that I had delayed perhaps as much as a week.  I read, somewhere, that stopping and starting the Bluetooth solved the problem for people that had made changes without positive effect.  I started stopping and starting BT after every change to settings.

Suddenly, it started working!

I wish I could have identified the cause of the problem.  Given I was going through all of the settings referenced (via Google searchs and the wiki):
I think it highly-likely I made a mistake and/or missed a setting.

My phone is now operating as expected passing all audio (in/out) to my PC computer (and then headset-with-mic).

**Comment by ferdnyc** [comment]
@ThePowerTool Glad to hear you got it working again!

GSConnect / KDE Connect aren't involved in passing of telephone audio — if done, that's entirely controlled by the Bluetooth pairing of your phone and your Linux desktop, as controlled in the device's Settings and the GNOME Control Center Bluetooth panel.

Audio sharing would work even without KDE Connect installed on the device, as long as the Bluetooth pairing is established and configured. It sounds like something in your phone settings had to be "refreshed" to get the pairing back online.

Regardless, since GSConnect is actually totally uninvolved in audio sharing, I'm going to close this as out-of-scope. But as I said, glad to hear it's working again!
