### ISSUE TITLE
Improve usability when sending link to Android device

### ISSUE THREAD

**Issue by genodeftest** [GSConnect/gnome-shell-extension-gsconnect#1849]
### Describe your request

1. Open the GSConnect section in GNOME shell's menus
2. Click the "Share" button, which opens a file chooser dialog
3. Click the _Send a Link to [device name]_ button (the one with the `web-browser-symbolic` icon)

What happens:
The _Send a Link to [device name]_ button is focused.

### Proposed solution

After clicking the _Send a Link to [device name]_ button, the address bar should be focused. This way, one could just paste the URL e.g. using `Ctrl+V` key bindings.

### Alternatives

Maybe add a separate button for sending links (separate from sending files), so GSConnect does not need to show a file chooser dialog to send an URL, which would also save one click.

### GSConnect version

57

### Installed from

GNOME Extensions website

### GNOME Shell version

gnome-shell-46.4-1.fc40.x86_64

### Linux distribution/release

Fedora 40

**Comment by ferdnyc** [comment]
This seems perfectly reasonable, and it's a one-line fix. Proposed in #1853.

**Comment by ferdnyc** [comment]
> Maybe add a separate button for sending links (separate from sending files), so GSConnect does not need to show a file chooser dialog to send an URL, which would also save one click.

Unfortunately there are two issues with that, one of our own making and one completely out of our control:

1. The current GSConnect design is "one plugin, one menu entry", and the same plugin (`share.js`) currently handles both file- and link-sharing activities.
2. Even if we were to change _that_, there's a reluctance to grow the list of menu selections any because of existing issues with the Shell user menu not being scrollable and running right off the bottom of small screens. (#1640, #1658, and https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/6056) 

   So right now any decision to make the menu _longer_ would have to be balanced against the problems it would cause for a lot of users, and I don't think redundant "Share..." items would win that contest.
