### ISSUE TITLE
Tooltips are displayed underneath the quick settings panel

### ISSUE THREAD

**Issue by zebra-cmyk** [GSConnect/gnome-shell-extension-gsconnect#1850]
### Describe the bug

In the quick settings, the connection and battery tooltips are displayed on the wrong layer.

### Steps to reproduce

1. Open Quick Settings
2. Click on the arrow to open the submenu
3. Hover on the connection or battery icon to show the corresponding tooltips

### Expected behavior

Tooltips are displayed on the topmost layer.

### GSConnect version

57

### Installed from

GNOME Extensions website

### GNOME Shell version

46

### Screenshots

![Screenshot](https://github.com/user-attachments/assets/2b9d9102-1e75-4124-8c93-14e94d6713db)

**Comment by ferdnyc** [comment]
Hrm. I'm not optimistic about us having much control over this, really, and suspect it's just a symptom of GNOME's disdain for tooltips in general that it (probably) ended up getting broken upstream.

(In fact, how do you know there's a tooltip being displayed _at all_? I'd half expect tooltips to simply Not Work™ in the user menu, just like they Don't Work™ in so much of the rest of Gtk 4 nowadays.)

**Comment by ferdnyc** [comment]
Huh. It seems we're actually getting _errors_ from the tooltip code, with current GSConnect and GNOME Shell 46.2. From a "Generate Support Log" session, repeatedly:

```text
Aug 23 23:18:47 gnome-shell[4454]: JS ERROR: TypeError: 
Main.layoutManager.uiGroup.remove_actor is not a function
onComplete@file:///home/ferd/.local/share/gnome-shell/extensions/
gsconnect@andyholmes.github.io/shell/tooltip.js:237:48
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:67:13
_easeActor/<@resource:///org/gnome/shell/ui/environment.js:154:64
@resource:///org/gnome/shell/ui/init.js:21:20
```

Still trying to work out the implications of that. it does indeed appear to be the case that `layout_manager` has no `uiGroup` property...

**Comment by ferdnyc** [comment]
I believe I have a fix for this, though I'm not sure it's a "legal" one. I just know that, in testing, it seems to solve all of the problems.

**Comment by ferdnyc** [comment]
@zebra-cmyk If you're interested in testing the fix before it's committed, to confirm that it works for you, a build with that change incorporated into it can be downloaded from the latest CI run for my PR: https://github.com/GSConnect/gnome-shell-extension-gsconnect/actions/runs/10540252804

(Just download "gsconnect@andyholmes.github.io" under "Artifacts", and it'll automatically download as a `.zip` file you can install in place of your current GSConnect. Because of how the Shell manages extensions, you'll have to log out and log in again at a minimum, to activate the new code.
