### ISSUE TITLE
Automatic clipboard sending

### ISSUE THREAD

**Issue by StrafeStopper** [GSConnect/gnome-shell-extension-gsconnect#1858]
### Describe your request

Would it be possible to have automatic clipboard sharing like Microsoft phone link? So you wouldn't have to manually open the app and "send clipboard". Possibly even bi-directional clipboard sharing so you could paste things from you computer to your phone. 

### GSConnect version

1.32.0

### Installed from

GNOME Extensions website

### Linux distribution/release

Ubuntu 24.04.1

**Comment by ferdnyc** [comment]
@StrafeStopper 

Fun fact / historical note: That's _precisely_ how clipboard-sharing support worked, in the earliest versions of GSConnect, working with the KDE Connect app versions that were current at the time. It was completely automatic and behind-the-scenes, you just copied/pasted on one device and the clipboard was mirrored to the other end of the pairing.

But then Google decided that giving apps unattended access to the device clipboard was insecure, and locked it down so that any clipboard operations had to be performed based on a (local) user interaction. Which... is hard to argue with, because theoretically under the old rules _any app you installed on your phone_ could spirit away every piece of data you put on the clipboard, completely undetected. Including sensitive data like passwords, credit card numbers, addresses, etc...

Microsoft's Phone Link (Windows) and Link to Windows (Android) apps do still support a feature they call "Cross-Device Copy & Paste" that works the way KDE Connect used to, but (rather critically) it's [only available on CERTAIN Android devices](https://support.microsoft.com/en-us/topic/seamlessly-transfer-content-between-your-devices-8a0ead3c-2f15-1338-66ca-70cf4ae81fcb#ID0EDRBBBBBBD) — some of those include Microsoft Surface devices, or devices running Samsung's One UI version 2.1+.

What that tells us is that Microsoft and Samsung overcame that Android clipboard restriction I mentioned by creating their own system service to provide seamless clipboard-sharing functionality; one that the Microsoft app would have access to, but which KDE Connect does not.

So, unfortunately, unattended clipboard-sharing functionality in modern Android devices requires the use of private APIs that KDE Connect does not have access to.

(Other Phone Link features, like drag-and-drop file transfers between Windows and Android, require not only specific Android devices, but they [only work with a **pre-installed** version of the Link to Windows app](https://support.microsoft.com/en-us/topic/supported-devices-for-phone-link-experiences-cb044172-87aa-9e41-d446-c4ac83ce8807), not the one generally downloadable from Google Play. Which says that not only does it depend on private APIs, but on credentials compiled into Samsung's private custom builds of the app that _aren't_ included in the publicly-available version.)

**Comment by poopsicles** [comment]
hm, curiously, the KDEConnect wiki has a [section](https://userbase.kde.org/KDEConnect#Auto-sync_on_Android_10+) on this that says:

> Android 10 prevents apps from accessing the clipboard to prevent malicious apps from accessing your data. This makes the clipboard plugin in KDE Connect uncomfortable to use.

> On Android 14, there's a tile in the pull-down menu called "Send clipboard", that can be moved to a convenient slot (e.g. in the partial pull-down section).
> ...
> If you have a build containing commit [edc655da5ac1eb5c3027c8556cc62037a1d4c5ac](https://invent.kde.org/network/kdeconnect-android/commit/edc655da5ac1eb5c3027c8556cc62037a1d4c5ac), you can enable the READ_LOGS permission in order to enable a workaround to clipboard sync.

I haven't tried it with gsconnect, but I'll give it a try, at least it's a workaround..
