### ISSUE TITLE
Error: OpenSSL not found on startup

### ISSUE THREAD

**Issue by theuser18** [GSConnect/gnome-shell-extension-gsconnect#1889]
### Describe the bug

Hi everyone. I have been using GSConnect for months just fine on Fedora 40 (Not 41, yet). Within the last week it has stopped working and I get "Error: OpenSSL not found on startup" every time I start up my laptop. As a result, GSConnect does not work at all.

### Steps to reproduce

It happens on start up, there is nothing to reproduce.

### GSConnect version

58

### Installed from

GNOME Extensions website

### GNOME Shell version

46

### Linux distribution/release

Fedora 40

### KDE Connect app version

1.32.5

**Comment by RodrigoPrestes** [comment]
Looking at the wiki (but an [earlier revision](https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Error/ea70fb62d6a15f47d5d6a396495aab9d195c89b5), seems people are editing things away) the solution for Fedora is to install openssl.  
`dnf install openssl` for Workstation and `rpm-ostree install openssl` then reboot for Atomic.

If you had working before though, maybe try to reinstall openssl and restart GNOME?

**Comment by theuser18** [comment]
Reinstallation worked. However it is rather strange that it just stopped working, timing that lines up fairly well with the last release.

**Comment by RodrigoPrestes** [comment]
Cool!
Looking it up again looks like current wiki has instructions about this: https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Help#openssl-not-found.
Should be fine to close this issue then?

**Comment by ferdnyc** [comment]
@theuser18

> However it is rather strange that it just stopped working, timing that lines up fairly well with the last release.

And you're still on Fedora 40, you _haven't_ upgraded to Fedora 41?

Only thing I can think of, then, is that you might have uninstalled whatever DNF package it was that originally pulled in openssl automatically as a dependency on your system. When that happens, DNF will also remove any "unneeded" dependency packages. (Fedora has been steadily eliminating dependencies on openssl in the base install, so it's very possible that your system reached a state where it was no longer required by anything.)

Because GSConnect is installed in your `$HOME/.local/` tree, DNF can't know about it and might therefore conclude that openssl is no longer required by anything.

That's a _guess_, but it's my best guess for why that would happen in any situation other than upgrading to a new Fedora release. But the good news is, now that you've installed openssl directly, DNF considers it a user-installed package and won't ever autoremove it when clearing out dependencies.

Closing this, as the need to provide better communication to users when there are issues with openssl not being available (among other things) is already being tracked in #862 and #1834.
